import '../services/llm_service.dart';

/// A decision trace entry — one scheduling decision the system made,
/// with an optional plain-language explanation generated by the LLM.
class DecisionTrace {
  final DateTime timestamp;
  final String taskName;
  final String decisionType;
  final Map<String, dynamic> context;
  String? explanation; // filled lazily when LLM is ready

  DecisionTrace({
    required this.taskName,
    required this.decisionType,
    required this.context,
    this.explanation,
  }) : timestamp = DateTime.now();
}

/// Records every scheduling decision the system makes and can explain
/// them in plain language using the on-device LLM.
///
/// Decision types:
///   'rescheduled'       — task moved to avoid conflict
///   'completed'         — task marked done
///   'anomaly_detected'  — duration anomaly flagged
///   'burnout_risk'      — burnout forecast triggered
///   'goal_scaled'       — goal load adjusted
///   'preference_learned'— new preference detected
///
/// Usage:
///   ReasoningTraceEngine.instance.record(
///     taskName: 'Morning Run',
///     decisionType: 'rescheduled',
///     context: {'reason': 'conflict', 'delayMinutes': 30},
///   );
///
///   final traces = ReasoningTraceEngine.instance.recent;
class ReasoningTraceEngine {
  ReasoningTraceEngine._internal();
  static final ReasoningTraceEngine instance =
      ReasoningTraceEngine._internal();

  // Keep last 50 decisions in memory.
  final List<DecisionTrace> _traces = [];
  static const int _maxTraces = 50;

  List<DecisionTrace> get recent =>
      List.unmodifiable(_traces.reversed.toList());

  /// Records a decision. If the LLM is ready, generates an explanation
  /// immediately. Otherwise the explanation stays null — call
  /// [fillExplanations] later once the model loads.
  Future<void> record({
    required String taskName,
    required String decisionType,
    required Map<String, dynamic> context,
  }) async {
    final trace = DecisionTrace(
      taskName: taskName,
      decisionType: decisionType,
      context: context,
    );

    if (LlmService.instance.isReady) {
      trace.explanation = await LlmService.instance.explainDecision(
        taskName: taskName,
        decisionType: decisionType,
        context: context,
      );
    }

    _traces.add(trace);
    if (_traces.length > _maxTraces) {
      _traces.removeAt(0);
    }
  }

  /// Fills explanations for any traces that don't have one yet.
  /// Call this once the LLM model finishes loading.
  Future<void> fillExplanations() async {
    if (!LlmService.instance.isReady) return;

    for (final trace in _traces) {
      if (trace.explanation == null || trace.explanation!.isEmpty) {
        trace.explanation = await LlmService.instance.explainDecision(
          taskName: trace.taskName,
          decisionType: trace.decisionType,
          context: trace.context,
        );
      }
    }
  }

  /// Human-readable label for a decision type.
  static String labelFor(String decisionType) {
    switch (decisionType) {
      case 'rescheduled':
        return 'Rescheduled';
      case 'completed':
        return 'Completed';
      case 'anomaly_detected':
        return 'Anomaly detected';
      case 'burnout_risk':
        return 'Burnout risk';
      case 'goal_scaled':
        return 'Goal adjusted';
      case 'preference_learned':
        return 'Preference learned';
      default:
        return decisionType;
    }
  }
}
