import 'package:flutter/material.dart';
import '../engine/reasoning_trace_engine.dart';
import '../theme/app_theme.dart';

/// Displays the last 50 scheduling decisions made by the engine, each
/// with an optional plain-language explanation generated by the on-device LLM.
class ReasoningTraceScreen extends StatefulWidget {
  const ReasoningTraceScreen({super.key});

  @override
  State<ReasoningTraceScreen> createState() => _ReasoningTraceScreenState();
}

class _ReasoningTraceScreenState extends State<ReasoningTraceScreen> {
  List<DecisionTrace> _traces = [];

  @override
  void initState() {
    super.initState();
    _traces = ReasoningTraceEngine.instance.recent;
  }

  Future<void> _refresh() async {
    await ReasoningTraceEngine.instance.fillExplanations();
    if (!mounted) return;
    setState(() {
      _traces = ReasoningTraceEngine.instance.recent;
    });
  }

  @override
  Widget build(BuildContext context) {
    final dark = context.isDark;
    final text = context.text;
    final ink = dark ? AppColors.darkInk : AppColors.ink;
    final sub = dark ? AppColors.darkInkSubtle : AppColors.inkSubtle;

    return Scaffold(
      backgroundColor: dark ? AppColors.darkCanvas : AppColors.canvas,
      appBar: AppBar(
        backgroundColor: dark ? AppColors.darkCanvas : AppColors.canvas,
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.arrow_back_ios_new_rounded, size: 20, color: ink),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Decision Log',
          style: text.titleMedium
              ?.copyWith(color: ink, fontWeight: FontWeight.w600),
        ),
        actions: [
          IconButton(
            icon: Icon(Icons.refresh_rounded, color: sub),
            onPressed: _refresh,
            tooltip: 'Fill in AI explanations',
          ),
        ],
      ),
      body: _traces.isEmpty
          ? _EmptyState(dark: dark, text: text, sub: sub)
          : RefreshIndicator(
              onRefresh: _refresh,
              child: ListView.separated(
                padding: const EdgeInsets.fromLTRB(20, 12, 20, 80),
                itemCount: _traces.length,
                separatorBuilder: (_, __) => const SizedBox(height: 10),
                itemBuilder: (_, i) => _TraceCard(
                  trace: _traces[i],
                  dark: dark,
                  text: text,
                ),
              ),
            ),
    );
  }
}

// ── Trace card ────────────────────────────────────────────────────────────────

class _TraceCard extends StatelessWidget {
  final DecisionTrace trace;
  final bool dark;
  final TextTheme text;

  const _TraceCard({
    required this.trace,
    required this.dark,
    required this.text,
  });

  Color _typeColor(String type) {
    return switch (type) {
      'completed' => dark ? AppColors.darkMoss : AppColors.moss,
      'rescheduled' => dark ? AppColors.darkAmber : AppColors.amber,
      'anomaly_detected' => dark ? const Color(0xFFD97B4B) : const Color(0xFFB85C1A),
      'burnout_risk' => dark ? AppColors.darkClay : AppColors.clay,
      'goal_scaled' => dark ? AppColors.darkDeep : AppColors.deep,
      'preference_learned' => dark ? const Color(0xFF7B8DE0) : const Color(0xFF4A5BC8),
      _ => dark ? AppColors.darkInkSubtle : AppColors.inkSubtle,
    };
  }

  IconData _typeIcon(String type) {
    return switch (type) {
      'completed' => Icons.check_circle_rounded,
      'rescheduled' => Icons.schedule_rounded,
      'anomaly_detected' => Icons.warning_amber_rounded,
      'burnout_risk' => Icons.local_fire_department_rounded,
      'goal_scaled' => Icons.auto_graph_rounded,
      'preference_learned' => Icons.auto_awesome_rounded,
      _ => Icons.info_outline_rounded,
    };
  }

  String _formatTime(DateTime dt) {
    final now = DateTime.now();
    final diff = now.difference(dt);
    if (diff.inMinutes < 1) return 'just now';
    if (diff.inMinutes < 60) return '${diff.inMinutes}m ago';
    if (diff.inHours < 24) return '${diff.inHours}h ago';
    return '${diff.inDays}d ago';
  }

  @override
  Widget build(BuildContext context) {
    final card = dark ? AppColors.darkCard : AppColors.cardSurface;
    final border = dark ? AppColors.darkBorder : AppColors.mist;
    final sub = dark ? AppColors.darkInkSubtle : AppColors.inkSubtle;
    final ink = dark ? AppColors.darkInk : AppColors.ink;
    final accent = _typeColor(trace.decisionType);
    final hasExplanation =
        trace.explanation != null && trace.explanation!.isNotEmpty;

    return Container(
      decoration: BoxDecoration(
        color: card,
        borderRadius: const BorderRadius.all(AppRadius.lg),
        border: Border.all(color: border),
      ),
      child: Padding(
        padding: const EdgeInsets.all(14),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ── Header ────────────────────────────────────────────────
            Row(
              children: [
                Container(
                  width: 32,
                  height: 32,
                  decoration: BoxDecoration(
                    color: accent.withValues(alpha: 0.12),
                    borderRadius: const BorderRadius.all(AppRadius.sm),
                  ),
                  child: Icon(_typeIcon(trace.decisionType),
                      color: accent, size: 16),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        trace.taskName,
                        style: text.bodyMedium?.copyWith(
                            color: ink, fontWeight: FontWeight.w600),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                      Text(
                        ReasoningTraceEngine.labelFor(trace.decisionType),
                        style: text.labelSmall?.copyWith(
                            color: accent, fontWeight: FontWeight.w700),
                      ),
                    ],
                  ),
                ),
                Text(
                  _formatTime(trace.timestamp),
                  style: text.labelSmall?.copyWith(color: sub),
                ),
              ],
            ),

            // ── Context key-values ────────────────────────────────────
            if (trace.context.isNotEmpty) ...[
              const SizedBox(height: 10),
              Wrap(
                spacing: 6,
                runSpacing: 4,
                children: trace.context.entries.map((e) {
                  return Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 8, vertical: 3),
                    decoration: BoxDecoration(
                      color: (dark ? AppColors.darkCanvas : AppColors.mist)
                          .withValues(alpha: 0.6),
                      borderRadius: const BorderRadius.all(AppRadius.pill),
                    ),
                    child: Text(
                      '${e.key}: ${e.value}',
                      style: text.labelSmall?.copyWith(color: sub),
                    ),
                  );
                }).toList(),
              ),
            ],

            // ── AI explanation ────────────────────────────────────────
            if (hasExplanation) ...[
              const SizedBox(height: 10),
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(Icons.lightbulb_outline_rounded,
                      size: 14,
                      color: dark ? AppColors.darkDeep : AppColors.deep),
                  const SizedBox(width: 6),
                  Expanded(
                    child: Text(
                      trace.explanation!,
                      style: text.bodySmall?.copyWith(
                        color: dark ? AppColors.darkInk : AppColors.ink,
                        height: 1.4,
                      ),
                    ),
                  ),
                ],
              ),
            ] else ...[
              const SizedBox(height: 10),
              Row(
                children: [
                  Icon(Icons.lightbulb_outline_rounded,
                      size: 14, color: sub),
                  const SizedBox(width: 6),
                  Text(
                    'AI explanation not yet available — tap ↻ above',
                    style: text.labelSmall?.copyWith(color: sub),
                  ),
                ],
              ),
            ],
          ],
        ),
      ),
    );
  }
}

// ── Empty state ───────────────────────────────────────────────────────────────

class _EmptyState extends StatelessWidget {
  final bool dark;
  final TextTheme text;
  final Color sub;

  const _EmptyState({
    required this.dark,
    required this.text,
    required this.sub,
  });

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(40),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              Icons.history_rounded,
              size: 56,
              color: dark ? AppColors.darkBorder : AppColors.mist,
            ),
            const SizedBox(height: 20),
            Text('No decisions recorded yet',
                style: text.titleMedium),
            const SizedBox(height: 8),
            Text(
              'Scheduling decisions appear here as you complete, delay, '
              'and create tasks.',
              style: text.bodyMedium?.copyWith(color: sub),
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }
}
